name: Create single-file PR (Trigger on review comment)

on:
  pull_request_review_comment:
    types: [created, edited]

permissions: {}

jobs:
  run-reusable:
    if: ${{ contains(github.event.comment.body, 'splice-bot') }}
    uses: leanprover-community/SpliceBot/.github/workflows/splice.yaml@b85378f2f5e5c31ad5cb4c3fd4710859f8aac63e # master
